### ISSUE TITLE
Github Trending display nothing.

### ISSUE THREAD

**Issue by ysm0622** [karakanb/devo#24]
Official Demo : 
![image](https://user-images.githubusercontent.com/18487241/64242662-e77b8800-cf40-11e9-959b-594bc00a0426.png)

My Chrome Extension : 
![image](https://user-images.githubusercontent.com/18487241/64242685-f19d8680-cf40-11e9-977f-262e4625534b.png)

My guess is that a GET request on the domain `https://devo.burakkarakan.com/api/github` sends 200 status but returns no data.

**Comment by karakanb** [comment]
Hey, thanks for reporting. My guess is, GitHub probably changed the layout of `Trending` page, that's why the backend is not able to parse the status. I'll try to see what is the problem and update the corresponding packages.

**Comment by karakanb** [comment]
I updated the package and bumped the versions, seems to be fixed. Could you please confirm? @ysm0622

**Comment by ysm0622** [comment]
Great, It fixed.
Thank you for your awesome project.

**Comment by ysm0622** [comment]
it occurred again,

![image](https://user-images.githubusercontent.com/18487241/66114098-1ac93980-e609-11e9-97ea-87398484bc68.png)
