### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by lanavely** [karakanb/devo#33]
It would be nice to add the ability to set a image as a background instead of the white or black background, then it would all look like widgets on the chrome start page.

**Comment by karakanb** [comment]
Hey,

Thanks for the idea. Apart from the responsiveness aspect, it should be straightforward to implement such a feature; however, one obvious limitation is where to put this, and therefore, there has to be a settings page to be built for this to be implemented.

I may try looking into it ina free time, but I am not sure about when. If anyone would like to prepare a PR for this, I am ready to review and move on.

**Comment by karakanb** [comment]
https://github.com/karakanb/devo/pull/35#issuecomment-724349613
