### ISSUE TITLE
Adding Indie Hackers(IH) in dashboard

### ISSUE THREAD

**Issue by ganeshmani** [karakanb/devo#36]
it would be nice to have [Indie Hackers](https://www.indiehackers.com/)(IH) top pages in the dashboard.

**Comment by karakanb** [comment]
I agree, I have been thinking about doing it for a long while now, but scraping seems to be against their Terms of Service, and they have no official API. I have also tried contacting Courtland on Twitter, but I couldn't get a reply.

There might be things I missed, feel free to suggest how to implement it.

**Comment by ganeshmani** [comment]
Yeah. No API for it. is it possible to automate via scraping or using web drivers? . BTW, how do you do it for Designer News  ?

**Comment by karakanb** [comment]
Designer News have their own API, just like the others. I crawl things like GitHub Trending for example, but given the complexity of the IndieHackers UI and its ever-changing nature, I will not be building anything that is not based on an API. Feel free to ping me or contribute directly in case the API ever becomes a reality though.
