### ISSUE TITLE
Selecting a different service from each of the dropdowns does nothing in Safari

### ISSUE THREAD

**Issue by crock** [karakanb/devo#37]
I don't expect a Safari extension to be created, so I am just using the live demo version set as my Safari homepage, but the dropdown doesn't trigger a change.

**Comment by karakanb** [comment]
Hi there,

I just checked the webpage on Safari and it seems to be working for me:
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/16530606/86116446-bd95e200-bacd-11ea-86f3-512b9f7a2c03.png">

I tried clicking and changing the platform, it is working for all three cards on the page. Would you mind giving a bit more details on the problem?

**Comment by crock** [comment]
Gonna close this for now because I can't re-produce anymore.
