### ISSUE TITLE
Wrong height when loading

### ISSUE THREAD

**Issue by qykong** [karakanb/devo#57]
Hi, the recent update with the two-column option is awesome! However, I noticed a minor UI issue when both columns are loading (as shown in the screenshot). I found that this issue applies to SingleColumn and ThreeColumn as well. I quickly found a fix for this issue and created pull request for this. :) I confirmed that the fix works on chrome and firefox. 

![image](https://user-images.githubusercontent.com/7960549/103610146-89671680-4f73-11eb-8844-3893add4534e.png)

**Comment by karakanb** [comment]
Since #58 is merged, I am closing this.
