### ISSUE TITLE
Always resets to light mode

### ISSUE THREAD

**Issue by egeucak** [karakanb/devo#61]
Thanks for great extension. I've been using devo for some time.
But I have an issue about the last update. Since today, the extension started switching to light mode every time I open a new tab. Uugh, my eyes hurt.

**Comment by karakanb** [comment]
Hi, thanks for the report, I merged a PR yesterday that made Devo take the dark mode preference from the browser directly, but we forgot to make it possible to override. I'll just remove the feature and release a patch version today, for now you can set your browser preferences to dark mode if you'd like to avoid.

**Comment by egeucak** [comment]
thanks for quick reply, and offering a swift solution. i didn't even knew browsers had a dark mode preference. i have my os in dark theme, but there might be an issue between ubuntu 20.04 and chrome

**Comment by karakanb** [comment]
I have released the bugfix version v1.8.4 in both of the stores. It is already live in the Mozilla Add-ons, and Chrome Store should have it by the end of the day today as well, sorry for the inconvenience.
