### ISSUE TITLE
Options button does not work on chrome new tab extension

### ISSUE THREAD

**Issue by karanjitsingh** [karakanb/devo#71]
Wanted to switch one of the cards to lobste.rs but the settings button on the bottom right is not clickable

**Comment by karanjitsingh** [comment]
nvm figured out how to change card, fyi the settings icon is misleading

**Comment by karakanb** [comment]
would you mind telling me where do you see a settings icon?

**Comment by karanjitsingh** [comment]
You're right there isn't one, I was confusing the "day" icon with a settings one. Either too much coffee in my blood or perhaps too little.  For the longest time I tried to click it. Even looked into the code, to later realize that's just for the toggle.

<img width="249" alt="image" src="https://user-images.githubusercontent.com/4632805/156457938-275648bb-aaf3-4178-8cd1-f5fc0eed8cb3.png">
