### ISSUE TITLE
Extension blocked by windows security

### ISSUE THREAD

**Issue by saisrivathsa** [karakanb/devo#77]
I have been using this extension for the past couple of months but I recently started seeing this issue with windows defenders while using the extension. I see this security alert every time I open a new tab. 
![image](https://user-images.githubusercontent.com/15000085/158663514-2c27125d-732c-45fe-9d4f-13f55cd0b7a3.png)

**Comment by saisrivathsa** [comment]
Tested this on firefox, edge, and chrome all are on latest version. 
I am facing this issue on my company's corporate network that might be the cause of this issue..

**Comment by karakanb** [comment]
Seems so, since I cannot produce this on neither firefox nor mac across multiple browsers. I'll be closing the issue for now, sorry for not being able to help, but please drop a message here in case you find sth that I can change on the backend to help improve it for you.
