### ISSUE TITLE
Alt ve sağ tarafta scrollbar görünme problemi

### ISSUE THREAD

**Issue by batuhangoksu** [karakanb/devo#9]
Merhaba,

Chrome eklentisinde alt ve sağ tarafta scroll çıkıyor. CSS kodlarını incelemem sonucu .row sınıfında

```css
margin-left: -.5rem;
margin-right: -.5rem;
```

değerlerini kaldırmam sonucu düzeldiğini fark ettim. Seyir halinde olduğum için düzenleme yapıp gönderemiyorum.

Bu konuyu incelerseniz sevinirim.

Teşekkürler.

**Comment by karakanb** [comment]
Merhaba, konu ile alakali bir gelistirici PR acip daha sik bir yontemle cozdu, merge'ledik, bir sonraki guncelleme ile yayinlayacagim, tesekkurler.
